# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('total_months', models.IntegerField()),
                ('commision', models.FloatField()),
                ('started', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('entry_date', models.DateField()),
                ('comment', models.CharField(max_length=1000)),
                ('entry_type', models.CharField(choices=[('A', 'Auction'), ('P', 'Payment'), ('D', 'Disbursement')], max_length=10)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('approved_date', models.DateField()),
                ('loan_lastpayment_date', models.DateField()),
                ('loan_name', models.CharField(max_length=30, null=True)),
                ('accumulated_interest', models.IntegerField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment_date', models.DateField()),
                ('payment_amount', models.IntegerField(default=0)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=1000)),
                ('auction_amount', models.IntegerField(null=True)),
                ('auction_date', models.DateField(null=True)),
                ('auction_number', models.IntegerField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='journalitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Subscriptions'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='txn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Journal'),
        ),
    ]
