# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry_type',
            field=models.CharField(choices=[('A', 'Auction'), ('P', 'Payment'), ('D', 'Disbursement')], max_length=10),
        ),
    ]
