# Generated by Django 4.0.3 on 2022-03-21 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chit_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='auction_txn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chit_main_app.journal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='started',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry_type',
            field=models.CharField(choices=[('A', 'Auction'), ('P', 'Payment'), ('D', 'Disbursement')], max_length=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chit_main_app.customer'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chit_main_app.subscriptions'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='txn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chit_main_app.journal'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chit_main_app.group'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chit_main_app.customer'),
        ),
    ]
