# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit_main_app', '0002_auto_20180523_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('approved_date', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Customer')),
            ],
        ),
    ]
