# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit_main_app', '0003_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='cid',
            new_name='ccid',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
