# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit_main_app', '0004_auto_20180529_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='ccid',
            new_name='identity',
        ),
    ]
