# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit_main_app', '0005_auto_20180529_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_payment_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='accumulated_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan_history',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Loan'),
        ),
    ]
