# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit_main_app', '0006_auto_20180604_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_history',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chit_main_app.Loan'),
        ),
    ]
